version: "3.8"
name: adopetme-dev

services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./adopetme-frontend:/app:cached
      - /app/node_modules
    ports:
      - "3030:5173"
    environment:
      - NODE_ENV=development